version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "8090:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      
  rabbitmq-service:
    build:
      dockerfile: Dockerfile.prod
    container_name: rabbitmq-service
    depends_on:
      - rabbitmq

