version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - custom_network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-service:
    build:
      dockerfile: Dockerfile.dev
    container_name: rabbitmq-service
    volumes:
      - .:/app
    ports:
      - "9229:9229"
    networks:
      - custom_network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  custom_network:
    driver: bridge