FROM node:18.20.5 AS install
WORKDIR /app

COPY --chown=node:node package-lock.json package.json ./
RUN npm install

FROM install as build
COPY --chown=node:node . ./
RUN rm -f .env
RUN npm run build
 
# Aplication
FROM node:18.20.5 as deploy
WORKDIR /app
COPY --from=build app/dist ./dist
COPY --from=build app/node_modules ./node_modules
CMD node ./dist/index.js
